### ISSUE TITLE
Can't import calendar into Google Calendar

### ISSUE THREAD

**Issue by WhereIsLucas** [spatie/icalendar-generator#29]
Hi,
Thanks for this great package! 
I'm trying to create a calendar stream for my application, but I can't import it in Google Calendar. 
I tried using the simple example in the README file and it's not working, but I have no error messages whatsoever.

It's working in my calendar app (Gnome Calendar), and the calendar passes the test here : [Validator](https://icalendar.org/validator.html).
I feel like it's linked to timezones but I'm not sure.

Thanks for your input!

**Comment by rubenvanassche** [comment]
Could you please check if the problem still exists with the latest version(1.0.4) some timezone fixes were added to that release.

**Comment by agneshoving** [comment]
Hi, I have the same problem as mentioned here (on version 1.0.5). 

The generated calendar looks like this:

`BEGIN:VCALENDAR
VERSION:2.0
PRODID:spatie/icalendar-generator
NAME:MijnKantoor - Anna Veenstra
X-WR-CALNAME:MijnKantoor - Anna Veenstra
DESCRIPTION:Taken vanuit MijnKantoor voor Anna Veenstra
X-WR-CALDESC:Taken vanuit MijnKantoor voor Anna Veenstra
REFRESH-INTERVAL;VALUE=DURATION:PT5M
X-PUBLISHED-TTL:PT5M
BEGIN:VEVENT
UID:5f914458bad67
SUMMARY:[Due]Presentatie voorbereiden
DESCRIPTION:Presentatie van sprint resultaten voorbereiden
DTSTART:20201022T221500Z
DTSTAMP:20201021T163726Z
END:VEVENT
END:VCALENDAR`

I'm not using withTimestamps() because it generates and invalid calendar format. The above calendar works fine on outlook. Google calender gives no error message only that importing the calendar failed.

**Comment by rubenvanassche** [comment]
Will close this issue due to inactivity
