### ISSUE TITLE
Feature to reply calendar through outlook/gmail/etc

### ISSUE THREAD

**Issue by icaroscherma** [spatie/icalendar-generator#40]
Currently I can send an email with the ICS attachment and the email clients will automatically detect the event and ask if you want to add it to your calendar (to be clear, it's not going to be a subscription calendar, but a fixed event based on the current ICS file), but I'm trying to make the reply function to work, like the `accepted`, `declined`, `tentative`...

Is there a way to the ICS file tells that it should run a request to an specific page **OR** the only way is to capture an email, sanitize the reply option, update the database and shoot another email to the participants with the updated ICS?

[Edit] I think it's part of the RFC 6638 (link below).
https://icalendar.org/CalDAV-Scheduling-RFC-6638/b-7-example-attendee-declining-an-instance-of-a-recurring-event.html

**Comment by rubenvanassche** [comment]
Hi @icaroscherma,

Though it would be a really cool feature, I think this is going to take us too far away from the package since we have to implement the CalDAV scheduling RFC. That said, if we can add support for this, I'll guess it would be a url in the calendar component to send the request to? By adding a few properties to the components, then I'll would accept such a PR that adds this functionality.
