### ISSUE TITLE
DTSTAMP format

### ISSUE THREAD

**Issue by tima2000** [spatie/icalendar-generator#42]
It looks like some calendars do not understand DTSTAMP with timezone.
DTSTAMP;TZID=UTC:20200626T094630
For example Yandex don't like it and event not appears in calendar.
Is it possible some how control DTSTAMP format?

**Comment by rubenvanassche** [comment]
Hi @tima2000,

I've released a new version 2.1.0 that uses the Z value when a unix timestamp is used, hopefully Yandex can read that since it's also a part of the RFC. Specifically changing the format based upon the client isn't supported at the time and would in my opinion be very complicated. Hopefully this small fix can solve your problem.

**Comment by tima2000** [comment]
Thank you Ruben,

it works!
